language: php

os: linux
dist: xenial

services:
  - mysql
  - postgresql

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

jobs:
  include:
    - php: 7.4
      env:
        - MOODLE_BRANCH=MOODLE_39_STABLE
        - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini

  - if [ -z $CHECK_GRUNT ]; then
      export CHECK_GRUNT=no;
    fi

  - if [ -z $NODE ]; then
      export NODE=14;
    fi
  - nvm install $NODE
  - nvm use $NODE

  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true # report issues, but don't fail the build.
  - moodle-plugin-ci grunt || [ "$CHECK_GRUNT" = 'no' ]
  - moodle-plugin-ci phpunit
  # - moodle-plugin-ci behat --profile chrome
